//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_Insurance_Company.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurance_Cases
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Insurance_Cases()
        {
            this.Documentation_Insurance_Cases = new HashSet<Documentation_Insurance_Cases>();
        }
    
        public int ID_Insurance_Case { get; set; }
        public string Insurance_Case { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documentation_Insurance_Cases> Documentation_Insurance_Cases { get; set; }
    }
}
