//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_Insurance_Company.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medical_Institutions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medical_Institutions()
        {
            this.Documentation_Insurance_Cases = new HashSet<Documentation_Insurance_Cases>();
        }
    
        public int ID_Contract_Medical_Institution { get; set; }
        public string Name_Med_Ins { get; set; }
        public Nullable<int> ID_Medical_Services { get; set; }
        public string Contract_Period { get; set; }
        public System.DateTime Date_of_Signing { get; set; }
        public Nullable<double> Price { get; set; }
        public string Phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documentation_Insurance_Cases> Documentation_Insurance_Cases { get; set; }
        public virtual Medical_Services Medical_Services { get; set; }
    }
}
